### ISSUE TITLE
Transcript print function: would it be possible to offer user option to specify desired print range, up to a maximum of 20

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#10]

**Comment by emmalemma** [comment]
I was struggling to come up with a nice way to select a page range, given the unreliable page numbers-- but having a number of pages after the current page seems like the perfect compromise. Implemented in 0d7f77d7b6012030bb7b96ea9e91d8004bcafdfb. Please give it a try and close this if it seems ok.

**Comment by pdeschner** [comment]
Works great -- thanks!
