### ISSUE TITLE
Indexing of photograph's inscription broken in some cases

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#19]
E.g., searching on "OMT-III-D-59 type:photographs" returns no hits, even though the first image brought back by "type:photographs" shows the image with that string in its inscription.  It seems the lead-in (for lack of a better phrase) to the inscription is not being indexed?  In the updated tblPhotographs data (in the project GD area), there are a number of cases in which the inscription seems to consist solely of this sort of lead-in, and so are not being found when searching on keywords contained in their inscriptions.

**Comment by emmalemma** [comment]
Fixed in 4f4bc2324218cfb71e494a018598d910f07a8cc2
