### ISSUE TITLE
Search box disappears when executing global unconstrained search and then proceeding on to transcript, document or photograph page

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#22]
Could we continue to display the search box in these contexts as well.

Search box missing below:
![missing_search_box](https://cloud.githubusercontent.com/assets/1544067/16441559/882c79fe-3d99-11e6-909b-6619ea054e63.png)

**Comment by emmalemma** [comment]
I take this to mean we want to show the search box for links from search results, but still not show the bar if there's no query parameter. So this is also done in fc2b1895efe9b5ed73576a1ed47c52ff7931ce1c
