### ISSUE TITLE
Search box not working properly from transcript snippets page or transcript page

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#23]
E.g., enter "type:document chart" and execute the search, and the query returns no hits, whereas entering it from the landing page's search box returns multiple hits.  This seems to only be a problem from the transcript snippets page or transcript page display.

E.g.:
![transcript_search_bug](https://cloud.githubusercontent.com/assets/1544067/16441616/112dc500-3d9a-11e6-953e-d2fe7d8528b9.png)

**Comment by emmalemma** [comment]
Hmm, this is tough. It seems really useful to have a transcript-specific search box, or you'll end up clicking through the search page a lot. But this is awkward also.

To address this issue I made the "No results" text more specific, and added a link to the full results. It could be done to have that just redirect you straight away, but I'd worry it would be confusing not knowing which page you'll end up on.

**Comment by pdeschner** [comment]
Nice!
