### ISSUE TITLE
Global unconstrained query ("*") not populating search box after execution

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#24]
E.g., after clicking on empty search box on landing page, with all 3 materials types checked, and executing the search, the search results page's search box is empty.  Could the search box display "*" in this situation to inform the user what the currently active query is, as well as on any clicked-through page which the user has accessed from the search results.

**Comment by emmalemma** [comment]
Done in fc2b1895efe9b5ed73576a1ed47c52ff7931ce1c
