### ISSUE TITLE
On document page sidebar, "Trial Issues" is always plural regardless of whether there is only 1 issue or more associated with this document

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#25]
Could "Trial Issue" be displayed when only 1 issue is listed, as "Authors" becomes "Author" when only 1 author is associated with document.  

E.g.:
![plural_v_singular_label](https://cloud.githubusercontent.com/assets/1544067/16441666/823b6e1e-3d9a-11e6-83a9-97109f5a489d.png)

**Comment by emmalemma** [comment]
Pluralized in 8d516decf40c375763d52bf24d7cf90649621248
