### ISSUE TITLE
On search results page for document hits, replace "Language of Text" with "HLSL Item No." and suppress "Trial Issue" and "Defendants" from being displayed

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#26]
This doc ID seems more important to us for most use cases, and the extra space freed up by suppressing "Trial Issues" and "Defendants" would allow more results to be displayed in the same space.

**Comment by emmalemma** [comment]
done in e6a45889f5f801e48b1c59f26ed8fbb7366f27f1
