### ISSUE TITLE
 On Approaches page, the 5 images of Evidence File and Case File documents, when clicked, do not properly link to their respective documents

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#27]
Clockwise, beginning top left, here are the links:
1. https://nuremberg-demo.herokuapp.com/documents/1264-letter-to-heinrich-himmler?q=hlsl:1264#p.1
2. https://nuremberg-demo.herokuapp.com/documents/1265-letter-to-heinrich-himmler?q=hlsl:1265#p.1
3. https://nuremberg-demo.herokuapp.com/documents/1266-letter-to-heinrich-himmler?q=hlsl:1266#p.1
4. https://nuremberg-demo.herokuapp.com/documents/1263-letter-to-heinrich-himmler?q=hlsl:1263#p.1
5. https://nuremberg-demo.herokuapp.com/documents/119-letter-to-heinrich-himmler?q=hlsl:119#p.1

![cf_ef_docs_links](https://cloud.githubusercontent.com/assets/1544067/16441710/ffa1829e-3d9a-11e6-8ff1-0466541ab6b2.png)

**Comment by emmalemma** [comment]
Correct links in e1edb28668cd02c78b1809cf93beb85dbd3ecd28
