### ISSUE TITLE
Defense exhibit codes not including defendant's name along with exhibit no.

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#28]
E.g., if user searches on "exhibit:(None 36)," the results returned are all defense exhibits with "Exhibit Code: None 36," when the correct code would list defendant's name preceding the no. ("Scheide 36" or "Pook 36").

Perhaps:
tblCasesList.DefExhNum, tblCasesList.DocID and tblCasesList.DefExhNameID might help, with the latter a foreign key from tblDefenseExhNames.DefenseExhNameID which gives us tbDefenseExhNames.DefenseExhName

As here:
![defense_exhibit_code_bug](https://cloud.githubusercontent.com/assets/1544067/16460978/337d2dfe-3df8-11e6-87f0-daf8fb0dc0d5.png)

**Comment by emmalemma** [comment]
For some reason I thought that table was fully denormalized... guess it's both. Fixed in 8d72a4ff66206a703deb2271567a643aca6aab7d and reindexed.
