### ISSUE TITLE
Queries over multiple materials types not working

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#29]
E.g., "goering type:documents, photographs" or "goering type:(documents photographs)" or "goering type:documents type:photographs" returns no hits, while "goering type:documents" returns 97 hits and "goering type:photographs" returns 11 hits.

**Comment by emmalemma** [comment]
Ah, the new syntax is `type:documents|photographs` or `type:(documents | photographs)`. I thought I had a test for that, though. Fixed the checkboxes on landing page to generate the correct query in b5ac1da9a8d40c1ea6eab051a45e05741bc72d3a
