### ISSUE TITLE
Change "Trial Activities" to "Trial Issues" in search results page's right-hand sidebar

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#3]
Looking for other instances of "Activities" -- they should be changed as well.  In the "Approaches" page: up top in the menu, and in the text header below, "Trial Issues & Activities" would become "Trial Issues"

**Comment by emmalemma** [comment]
Also closed by bac3e9f789f1b492f66cbf8a32479799ce68c7d4 and bac3e9f789f1b492f66cbf8a32479799ce68c7d4. Let me know if you notice any I missed.
