### ISSUE TITLE
Transcript label change request

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#30]
Could we change the label in the right-hand sidebar of each transcript page from "Case transcript for NMT 2: Milch Case" to "Transcript for NMT 2: Milch Case" (removing initial "Case," as it's implied).

**Comment by emmalemma** [comment]
Sure, this is just a database field. I updated it on demo and changed the default being set by `ingest_transcript_xml` in 6679d8e3ebc184ce5b49f16ac40fd07ee0f64ded
