### ISSUE TITLE
Sort by feature on search results page only looking at documents and not transcripts or images?

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#31]
Transcripts would normally sort to the top when selecting "Most Pages" -- are only documents included?

**Comment by emmalemma** [comment]
This is because transcript page count wasn't indexed-- it wasn't clear to me it was the same kind of thing. Added transcript size to the index in 025780459b40ced27422bf52d00d8b9dfbcf1bc3, and also fixed a small bug that was affecting sorting of transcript search results.
